/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: '#fcf9f8',
        'surface-dim': '#dcd9d9',
        'surface-bright': '#fcf9f8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3f2',
        'surface-container': '#f0eded',
        'surface-container-high': '#eae7e7',
        'surface-container-highest': '#e5e2e1',
        'on-surface': '#1b1b1c',
        'on-surface-variant': '#434656',
        'inverse-surface': '#303030',
        'inverse-on-surface': '#f3f0ef',
        outline: '#737688',
        'outline-variant': '#c3c5d9',
        'surface-tint': '#004dea',
        primary: '#0041c8',
        'on-primary': '#ffffff',
        'primary-container': '#0055ff',
        'on-primary-container': '#e3e6ff',
        'inverse-primary': '#b6c4ff',
        secondary: '#00677f',
        'on-secondary': '#ffffff',
        'secondary-container': '#00ccf9',
        'on-secondary-container': '#005266',
        tertiary: '#4044a4',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#595dbe',
        'on-tertiary-container': '#e6e5ff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#fcf9f8',
        'on-background': '#1b1b1c',
        'surface-variant': '#e5e2e1',
        'background-subtle': '#F0F6FF',
        'success-emerald': '#10B981',
        'warning-amber': '#F59E0B',
        'border-light': '#E5E7EB',
      },
      fontFamily: {
        display: ['"Hanken Grotesk"', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      boxShadow: {
        level1: '0px 4px 20px rgba(0, 0, 0, 0.04)',
        level2: '0px 8px 30px rgba(0, 0, 0, 0.08)',
      },
      maxWidth: {
        content: '1280px',
      },
    },
  },
  plugins: [],
}
